service: weather-service

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, 'us-east-1'}
  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  weatherFetcher:
    handler: handler.weatherUpdater
    timeout: 300
    events:
      - schedule: rate(24 hours)

custom:
  dotenv:
    path: .env
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION


useDotenv: true